const assets = {
  logo: "/images/logo.png",
  card1: "/images/card1.png",
  card2: "/images/card2.png",
  card3: "/images/card3.png",
  card4: "/images/card4.png",
  card5: "/images/card5.png",
  mockup: "/images/mockup.webp",
  mockup1: "/images/mockup1.png",
  mockup2: "/images/mockup2.png",
  mockup3: "/images/mockup3.png",
  mockup4: "/images/mockup4.png",
  // Lastr iPhone mockups for carousel
  iPhoneMockup1: "/images/iMockup - iPhone 15 Pro Max.png",
  iPhoneMockup2: "/images/iMockup - iPhone 15 Pro Max-1.png",
  iPhoneMockup3: "/images/iMockup - iPhone 15 Pro Max-2.png",
  iPhoneMockup4: "/images/iMockup - iPhone 15 Pro Max-3.png",
  iPhoneMockup5: "/images/iMockup - iPhone 15 Pro Max-4.png",
  iPhoneMockup6: "/images/iMockup - iPhone 15 Pro Max-5.png",
  iPhoneMockup7: "/images/iMockup - iPhone 14.png",
  iPhoneMockup8: "/images/iMockup - iPhone 14-1.png",
  iPhoneMockup9: "/images/iMockup - iPhone 14-2.png",
  iPhoneMockup10: "/images/iMockup - iPhone 14-3.png",
  stars: "/images/stars.png",
  profile1: "/images/review-profile-1.png",
  profile2: "/images/review-profile-2.png",
  profile3: "/images/review-profile-3.png",
  cLogo1: "/images/cLogo1.png",
  cLogo2: "/images/cLogo2.png",
  cLogo3: "/images/cLogo3.png",
  cLogo4: "/images/cLogo4.png",
  cLogo5: "/images/cLogo5.png",
  cLogo6: "/images/cLogo6.png",
  cLogo7: "/images/cLogo7.png",
  cLogo8: "/images/cLogo8.png",
  video1: "/videos/video1.mp4",
  video2: "/videos/video2.mp4",
  video3: "/videos/video3.mp4",
  video4: "/videos/video4.mp4",
  video5: "/videos/video5.mp4",
  icons: {
    android: "/svg/android.svg",
    apple: "/svg/apple.svg",
    barChart: "/svg/bar-chart.svg",
    camera: "/svg/camera.svg",
    brain: "/svg/brain.svg",
    download: "/svg/download.svg",
    magnifying: "/svg/magnifying.svg",
    robot: "/svg/robot.svg",
    tools: "/svg/tools.svg",
    instagram: "/svg/instagram.svg",
    tiktok: "/svg/tiktok.svg",
  },
};

export default assets;
